config/routes.rb
Trobox::Application.routes.draw do


  resources :users
  resources :applications do
    member do
      post 'apply'
    end
  end

  resources :documents

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  get 'expose/:id' => 'test#expose'
  get 'application_overview' => 'pages#application_overview'
  get 'document_upload' => 'documents#upload'
  get 'landing_page' => 'pages#landing_page'
  get 'personal_data' => 'pages#personal_data'
  get 'send' => 'send#view', as: :send_view
  post 'send' => 'send#post'
  post 'callback.json' => 'send#callback'

  devise_scope :user do
    get 'sign_out', :to => 'devise/sessions#destroy', :as => :sign_out
  end


  root 'pages#landing_page'








end

app/models/application.rb
class Application < ActiveRecord::Base

  belongs_to :user

  attr_accessor :immo_url

  before_create :set_data_from_immo


  def set_data_from_immo
    self.attributes = expose(immo_id_from_url)
  end

  def get_data_from_immo
    {'immo_id' => ''}
  end

  def immo_id_from_url
    immo_url.gsub(/[htpswimobilencutdx.\:\/]/, "")[2,8]
  end

  def expose(id)
    page = Nokogiri::HTML(open("http://www.immobilienscout24.de/expose/#{id}/"))

   {
      title: page.css('#expose-title').text,
      picture_url: page.css('#is24-gallery-main-image').attribute('src').value,
      #fullprice: page.css('.is24qa-gesamtmiete').children[2].text.gsub("\n","").gsub("\r","").gsub(" ","").gsub("EUR",""),#[15,6],
      #fullprice: page.css('.is24qa-gesamtmiete').children[2].text.gsub(/[\n\r\ ()a-z]/i,"").to_f,
      price: page.css('.is24qa-gesamtmiete').children[2].text.gsub(/[\n\r]/,"").gsub("   ", ""),
      living_space: page.css('.is24qa-wohnflaeche-ca').text.gsub(/[\n\r\ m²]/,"").to_f,
      rooms: page.css('.is24qa-zimmer').text.gsub(/[\n\r\ ]/,"").to_f,
      immo_id: id,
      landline: page.css('.is24-phone').children[1].children[2].text.gsub(/[\n\r\t]/,"").gsub("   ", ""),
      address: page.css('#is24-content').children[1].children[7].children[3].children[1].text.gsub(/[\n\r]/,"").gsub("   ", ""),
      city: page.css('#is24-content').children[1].children[7].children[3].children[3].text.gsub(/[\n\r]/,"").gsub("   ", "")
      #address: page.css('.is24-ex-address').css('p')[2].text,
      #housenumber: page.css('#expose-title').text,
      #postcode: page.css('#expose-title').text,
      #city: page.css('#expose-title').text
    }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/applications_controller.rb
require 'tropo-webapi-ruby'
require 'net/http'
require 'uri'

class ApplicationsController < ApplicationController
  before_action :set_application, only: [:show, :edit, :update, :destroy, :apply]

  # GET /applications
  # GET /applications.json
  def index
    @applications = Application.all
  end

  # GET /applications/1
  # GET /applications/1.json
  def show
  end

  # GET /applications/new
  def new
    @application = Application.new
  end

  # GET /applications/1/edit
  def edit
  end

  # POST /applications
  # POST /applications.json
  def create
    @application = Application.new(application_params)

    respond_to do |format|
      if @application.save
        format.html { redirect_to edit_application_path(@application), notice: 'Application was successfully created.' }
        format.json { render action: 'show', status: :created, location: @application }
      else
        format.html { render action: 'new' }
        format.json { render json: @application.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /applications/1
  # PATCH/PUT /applications/1.json
  def update
    respond_to do |format|
      if @application.update(application_params)
        format.html { redirect_to @application, notice: 'Application was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @application.errors, status: :unprocessable_entity }
      end
    end
  end

  def apply
    @application.update_attributes(applied: true)
    token = '686b62647a714d79664c796a534b746f4b6e764358465570675a4a6c747556506f794f545a42774e616e7946'
    url = 'https://tropo.developergarden.com/api/sessions?action=create&token=' + token + '&phone=' + url_encode(request[:phone]) + '&msg=' + url_encode(request[:message])
    uri = URI.parse(url)
    Net::HTTP.get(uri)
    redirect_to '/application_overview'
  end

  # DELETE /applications/1
  # DELETE /applications/1.json
  def destroy
    @application.destroy
    respond_to do |format|
      format.html { redirect_to applications_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_application
      @application = Application.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def application_params
      params.require(:application).permit(:immo_id, :user_id, :title, :picture_url, :price, :living_space, :rooms, :address, :email, :mobile, :landline, :applied, :immo_url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/applications_helper.rb
module ApplicationsHelper
end

app/views/applications/_form.html.erb
<div class="w-form formwrapper">
  <%= form_for(@application) do |f| %>
    <label class="formtitel">Immobilie:</label>
    <%= f.hidden_field :user_id %>
    <%= f.label :title, class: 'fieldlabel' %>
    <%= f.text_field :title, class: "w-input textfield" %>
    <%= f.label :picture_url, class: 'fieldlabel' %>
    <%= f.text_field :picture_url, class: "w-input textfield" %>
    <%= f.label :price, class: 'fieldlabel' %>
    <%= f.text_field :price, class: "w-input textfield" %>
    <%= f.label :living_space, class: 'fieldlabel' %>
    <%= f.text_field :living_space, class: "w-input textfield" %>
    <%= f.label :rooms, class: 'fieldlabel' %>
    <%= f.text_field :rooms, class: "w-input textfield" %>
    <%= f.label :address, class: 'fieldlabel' %>
    <%= f.text_field :address, class: "w-input textfield" %>
    <%= f.label :city, class: 'fieldlabel' %>
    <%= f.text_field :city, class: "w-input textfield" %>
    <%= f.label :email, class: 'fieldlabel' %>
    <%= f.text_field :email, class: "w-input textfield" %>
    <%= f.label :mobile, class: 'fieldlabel' %>
    <%= f.text_field :mobile, class: "w-input textfield" %>
    <%= f.label :landline, class: 'fieldlabel' %>
    <%= f.text_field :landline, class: "w-input textfield" %>
    <%= f.submit 'Update', class: "w-button submitbutton" %>
  <% end %>
</div>

app/views/applications/edit.html.erb
<div class="w-form formwrapper">
  <form class="w-clearfix form" name="email-form" data-name="Email Form">
		<%= render 'form' %>
	</form>
</div>
<style type="text/css">
	.textfield, .submitbutton {
		position: relative; 
		right: 70px;
	}
	.fieldlabel, .formtitel {
		position: relative; 
		left: 40px;
	}
</style>

app/views/applications/index.html.erb
<h1>Listing applications</h1>

<table>
  <thead>
    <tr>
      <th>Immo</th>
      <th>User</th>
      <th>Title</th>
      <th>Picture url</th>
      <th>Price</th>
      <th>Living space</th>
      <th>Rooms</th>
      <th>Address</th>
      <th>Email</th>
      <th>Mobile</th>
      <th>Landline</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @applications.each do |application| %>
      <tr>
        <td><%= application.immo_id %></td>
        <td><%= application.user_id %></td>
        <td><%= application.title %></td>
        <td><%= application.picture_url %></td>
        <td><%= application.price %></td>
        <td><%= application.living_space %></td>
        <td><%= application.rooms %></td>
        <td><%= application.address %></td>
        <td><%= application.email %></td>
        <td><%= application.mobile %></td>
        <td><%= application.landline %></td>
        <td><%= link_to 'Show', application %></td>
        <td><%= link_to 'Edit', edit_application_path(application) %></td>
        <td><%= link_to 'Destroy', application, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Application', new_application_path %>

app/views/applications/new.html.erb
<h1>New application</h1>

<%= form_for(@application) do |f| %>
  <div class="field">
    <%= f.label :immo_url %><br>
    <%= f.text_field :immo_url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= link_to 'Back', applications_path %>

app/views/applications/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Immo:</strong>
  <%= @application.immo_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @application.user_id %>
</p>

<p>
  <strong>Title:</strong>
  <%= @application.title %>
</p>

<p>
  <strong>Picture url:</strong>
  <%= @application.picture_url %>
</p>

<p>
  <strong>Price:</strong>
  <%= @application.price %>
</p>

<p>
  <strong>Living space:</strong>
  <%= @application.living_space %>
</p>

<p>
  <strong>Rooms:</strong>
  <%= @application.rooms %>
</p>

<p>
  <strong>Address:</strong>
  <%= @application.address %>
</p>

<p>
  <strong>Email:</strong>
  <%= @application.email %>
</p>

<p>
  <strong>Mobile:</strong>
  <%= @application.mobile %>
</p>

<p>
  <strong>Landline:</strong>
  <%= @application.landline %>
</p>

<%= link_to 'Edit', edit_application_path(@application) %> |
<%= link_to 'Back', applications_path %>